# Generated by Django 3.1.3 on 2021-02-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210223_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.university'),
        ),
    ]
