# Generated by Django 3.1.3 on 2021-04-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210226_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AddField(
            model_name='university',
            name='profile',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='university', serialize=False, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
