# Generated by Django 3.1.3 on 2021-02-03 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_remove_plan_member_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInviteCode',
            fields=[
                ('connected_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invite_code', serialize=False, to='meeting.plan')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='invite_url',
        ),
    ]
