# Generated by Django 3.1.3 on 2021-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20210208_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanInviteCode',
            new_name='MeetingInviteCode',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='duration_hour',
        ),
        migrations.AlterField(
            model_name='confirmedmeeting',
            name='place',
            field=models.CharField(default='장소미정', max_length=10),
        ),
    ]
