# Generated by Django 3.1.3 on 2021-02-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20210214_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvitecode',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invite_code', serialize=False, to='meeting.meeting'),
        ),
    ]
