# Generated by Django 3.1.3 on 2021-02-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20210226_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetinginvitecode',
            old_name='created_time',
            new_name='created_datetime',
        ),
    ]
