# Generated by Django 3.1.3 on 2021-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_remove_meetinginvitecode_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedtime',
            name='place',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
