# Generated by Django 3.1.3 on 2021-04-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_auto_20210404_2105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('meeting', 'name')},
        ),
    ]
