# Generated by Django 3.1.3 on 2021-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0014_auto_20210406_0052"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="expired_at",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
