# Generated by Django 3.1.3 on 2021-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0016_auto_20210411_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedtime',
            name='place',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
