# Generated by Django 3.1.3 on 2021-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0017_auto_20210411_0318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="name",
            field=models.CharField(max_length=15),
        ),
    ]
